kind: Service
apiVersion: v1
metadata:
  name: grafana-service-ext
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: __GRAFANA_PORT__